extends "res://tests/helpers/singleplayer_smoke_suite.gd"


func _run() -> void:
	_run_bootstrap_contracts()
	_finish("SMOKE_SINGLEPLAYER_BOOTSTRAP_OK")


func _run_bootstrap_contracts() -> Dictionary:
	var state := _new_legacy_state()
	_expect(state.snapshot()["phase"] == "route", "initial phase is route")
	var initial := state.snapshot()
	_expect(int(initial.get("stateVersion", -1)) == 0, "initial snapshot exposes browser-style stateVersion")
	var initial_state_hash := String(initial.get("stateHash", ""))
	_expect(initial_state_hash.length() == 16, "initial snapshot exposes browser-style 16-char stateHash")
	_expect(int(initial.get("maxRounds", 0)) == 12, "initial snapshot exposes the two-player round limit")
	_expect(int(initial.get("castleLine", 0)) == 10, "initial snapshot exposes browser-style castleLine")
	_expect(is_equal_approx(float(initial.get("economyMultiplier", 0.0)), 1.0), "initial snapshot exposes browser-style economyMultiplier")
	_expect(int(initial.get("hero_hp", 0)) == 80, "initial player hero HP matches browser leader default")
	_expect(int(initial.get("heroMaxHp", 0)) == 80, "initial player hero max HP matches browser leader default")
	var initial_leaders := Dictionary(initial.get("leaders", {}))
	var initial_player_leader := Dictionary(initial_leaders.get("player", {}))
	var initial_enemy_leader := Dictionary(initial_leaders.get("enemy", {}))
	_expect(String(initial_player_leader.get("id", "")) == "player_hero", "initial leaders expose browser player hero id")
	_expect(String(initial_player_leader.get("side", "")) == "hero_leader", "initial player leader side matches browser")
	_expect(String(initial_player_leader.get("camp", "")) == "player", "initial player leader camp matches browser")
	_expect(String(initial_player_leader.get("name", "")) == "孙悟空", "initial player leader name matches browser")
	_expect(int(initial_player_leader.get("hp", 0)) == 80 and int(initial_player_leader.get("maxHp", 0)) == 80, "initial player leader HP matches browser")
	_expect(int(Dictionary(initial_player_leader.get("position", {})).get("r", -1)) == 7 and int(Dictionary(initial_player_leader.get("position", {})).get("c", -1)) == 0, "initial player leader position matches browser R8C1")
	_expect(String(initial_enemy_leader.get("id", "")) == "enemy_boss", "initial leaders expose browser enemy boss id")
	_expect(String(initial_enemy_leader.get("side", "")) == "boss", "initial enemy leader side matches browser")
	_expect(String(initial_enemy_leader.get("camp", "")) == "enemy", "initial enemy leader camp matches browser")
	_expect(String(initial_enemy_leader.get("name", "")) == "虎先锋", "initial enemy leader name matches browser")
	_expect(int(initial_enemy_leader.get("hp", 0)) == 80 and int(initial_enemy_leader.get("maxHp", 0)) == 80, "initial enemy leader HP matches browser")
	_expect(int(Dictionary(initial_enemy_leader.get("position", {})).get("r", -1)) == 0 and int(Dictionary(initial_enemy_leader.get("position", {})).get("c", -1)) == 7, "initial enemy leader position matches browser R1C8")
	var initial_vm_leaders := Dictionary(Dictionary(initial.get("viewModel", {})).get("leaders", {}))
	_expect(String(Dictionary(initial_vm_leaders.get("player", {})).get("name", "")) == "孙悟空", "viewModel exposes browser player leader")
	_expect(String(Dictionary(initial_vm_leaders.get("enemy", {})).get("name", "")) == "虎先锋", "viewModel exposes browser enemy leader")
	_expect(String(_board_cell(state, 0, 7).get("leaderId", "")) == "player_hero", "board projects player leader id onto R8C1")
	_expect(String(_board_cell(state, 7, 0).get("leaderId", "")) == "enemy_boss", "board projects enemy leader id onto R1C8")
	_expect(int(initial["data_counts"]["route_schedule"]) > 0, "route schedule is exported from CSV")
	_expect(int(initial["data_counts"]["shop_items"]) > 0, "shop items are exported from CSV")
	_expect(int(Dictionary(initial["data_counts"]).get("relics", 0)) > 0, "bootstrap exposes the current relic catalog")
	_expect(_source_files_include(initial, "data/csv/07_relic_blessings.csv"), "bootstrap records the relic source table")
	_expect(int(initial["data_counts"]["events"]) > 0, "events are exported from CSV")
	_expect(int(initial["data_counts"]["shapes"]) == 19, "shape catalog is exported from CSV")
	_expect(int(initial["data_counts"]["action_shapes"]) > 0, "action shape slots are exported from CSV")
	_expect(int(initial["data_counts"]["quality_growth"]) == 12, "quality growth table is exported from CSV")
	_expect(int(initial["data_counts"]["quality_upgrades"]) == 68, "quality upgrade table is exported from CSV")
	_expect(int(initial["data_counts"].get("mechanisms", 0)) == 61, "formal mechanism table is exported from CSV")
	_expect(int(initial["data_counts"].get("runtime_database_tables", 0)) == 31, "full runtime database table set is exported into Godot JSON")
	_expect(int(initial["data_counts"].get("runtime_database_units", 0)) == 127, "runtime database exposes all unit identity rows")
	_expect(int(initial["data_counts"].get("runtime_database_wave_rounds", 0)) == 134, "runtime database exposes all wave round rows")
	var runtime_database := Dictionary(state.game_data.get("runtime_database", {}))
	_expect(String(runtime_database.get("schemaVersion", "")) == "ysbzs.runtime-database.v1", "runtime database schema version is preserved")
	var runtime_database_tables := Dictionary(runtime_database.get("tables", {}))
	_expect(Dictionary(runtime_database_tables.get("units", {})).has("rows"), "runtime database keeps queryable unit rows")
	_expect(Dictionary(runtime_database_tables.get("relics", {})).has("rows"), "runtime database preserves non-active reference tables without adding relic reward counts")
	var fire_ignite_row := _mechanism_row(initial, "mech_fire_ignite_bonus")
	_expect(String(fire_ignite_row.get("runtime_status", "")) == "可接入", "mechanism export preserves planner CSV access status")
	_expect(String(fire_ignite_row.get("web_runtime_status", "")) == "implemented", "mechanism export exposes browser MECHANIC_STATUS status separately")
	_expect(String(fire_ignite_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_fire_ignite_bonus behavior instead of leaving it as browser-status-only")
	var wind_slow_row := _mechanism_row(initial, "mech_wind_slow_ap")
	_expect(String(wind_slow_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_wind_slow_ap behavior instead of leaving it as browser-status-only")
	var wind_push_row := _mechanism_row(initial, "mech_wind_push_on_hit")
	_expect(String(wind_push_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_wind_push_on_hit behavior instead of leaving it as browser-status-only")
	var on_hit_blast_row := _mechanism_row(initial, "mech_on_hit_blast")
	_expect(String(on_hit_blast_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_on_hit_blast behavior instead of leaving it as event-flow-only")
	var counter_attack_row := _mechanism_row(initial, "mech_counter_attack")
	_expect(String(counter_attack_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_counter_attack behavior instead of leaving it as event-flow-only")
	var summon_when_hit_row := _mechanism_row(initial, "mech_summon_when_hit")
	_expect(String(summon_when_hit_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_summon_when_hit behavior instead of leaving it as event-flow-only")
	var retaliate_summon_row := _mechanism_row(initial, "mech_retaliate_summon")
	_expect(String(retaliate_summon_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_retaliate_summon behavior instead of leaving it as event-flow-only")
	var summon_after_kill_row := _mechanism_row(initial, "mech_summon_after_kill")
	_expect(String(summon_after_kill_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_summon_after_kill behavior instead of leaving it as event-flow-only")
	var revenge_buff_row := _mechanism_row(initial, "mech_revenge_buff")
	_expect(String(revenge_buff_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_revenge_buff behavior instead of leaving it as event-flow-only")
	var copy_weak_self_row := _mechanism_row(initial, "mech_copy_weak_self")
	_expect(String(copy_weak_self_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_copy_weak_self behavior instead of leaving it as event-flow-only")
	var water_cleanse_row := _mechanism_row(initial, "mech_water_cleanse_debuff")
	_expect(String(water_cleanse_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_water_cleanse_debuff behavior instead of leaving it as event-flow-only")
	var guard_taunt_row := _mechanism_row(initial, "mech_guard_taunt")
	_expect(String(guard_taunt_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_guard_taunt target selection instead of leaving it as event-flow-only")
	var summon_wall_row := _mechanism_row(initial, "mech_summon_wall")
	_expect(String(summon_wall_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_summon_wall behavior instead of leaving it as event-flow-only")
	var multi_element_row := _mechanism_row(initial, "mech_multi_element_bonus")
	_expect(String(multi_element_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_multi_element_bonus settlement behavior instead of leaving it as event-flow-only")
	var castle_line_row := _mechanism_row(initial, "mech_castle_line_damage")
	_expect(String(castle_line_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_castle_line_damage failure behavior instead of leaving it as event-flow-only")
	var economy_decay_row := _mechanism_row(initial, "mech_economy_decay_on_fail")
	_expect(String(economy_decay_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_economy_decay_on_fail failure behavior instead of leaving it as event-flow-only")
	var hatch_row := _mechanism_row(initial, "mech_hatch_after_rounds")
	_expect(String(hatch_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_hatch_after_rounds countdown behavior instead of leaving it as event-flow-only")
	var fire_cross_row := _mechanism_row(initial, "mech_fire_cross_detonate_diamond")
	_expect(String(fire_cross_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_fire_cross_detonate_diamond cross fire-explosion behavior instead of leaving it as event-flow-only")
	var countdown_pressure_row := _mechanism_row(initial, "mech_countdown_pressure")
	_expect(String(countdown_pressure_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_countdown_pressure round-start pressure behavior instead of leaving it as event-flow-only")
	var reduce_reward_row := _mechanism_row(initial, "mech_reduce_reward_if_alive")
	_expect(String(reduce_reward_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_reduce_reward_if_alive battle-end reward penalty instead of leaving it as event-flow-only")
	var trap_stack_row := _mechanism_row(initial, "mech_trap_stack_trigger")
	_expect(String(trap_stack_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_trap_stack_trigger enter-cell trap settlement instead of leaving it as event-flow-only")
	var consume_layers_row := _mechanism_row(initial, "mech_consume_layers_grow")
	_expect(String(consume_layers_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_consume_layers_grow element-consume growth instead of leaving it pending")
	var summon_each_round_row := _mechanism_row(initial, "mech_summon_each_round")
	_expect(String(summon_each_round_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_summon_each_round round-start summon instead of leaving it pending")
	var penalty_round10_row := _mechanism_row(initial, "mech_penalty_after_round10")
	_expect(String(penalty_round10_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_penalty_after_round10 max-round failure instead of leaving it pending")
	var elite_reward_row := _mechanism_row(initial, "mech_elite_reward_bonus")
	_expect(String(elite_reward_row.get("godot_behavior_status", "")) == "covered", "Godot covers formal mech_elite_reward_bonus battle-end reward evidence instead of leaving it pending")
	_expect(_mechanism_row(initial, "mech_fire_core_domain").is_empty(), "temporary Day7 trial-domain mechanisms stay out of the formal mechanism export")
	var mechanism_status := Dictionary(initial.get("mechanism_status", {}))
	var day7_trial_status := Dictionary(Dictionary(mechanism_status.get("by_id", {})).get("mech_fire_core_domain", {}))
	_expect(String(day7_trial_status.get("web_runtime_status", "")) == "implemented", "temporary trial-domain mechanisms keep their browser status for traceability")
	_expect(String(day7_trial_status.get("godot_behavior_status", "")) == "excluded_temporary_trial", "Godot excludes temporary Day7 trial-domain mechanisms from mainline parity work")
	var shield_max_trial_status := Dictionary(Dictionary(mechanism_status.get("by_id", {})).get("mech_shield_max", {}))
	_expect(String(shield_max_trial_status.get("web_runtime_status", "")) == "implemented", "temporary shield-max trial mechanism keeps its browser status for traceability")
	_expect(String(shield_max_trial_status.get("godot_behavior_status", "")) == "excluded_temporary_trial", "Godot excludes the temporary shield-max trial mechanism from mainline parity work")
	for temporary_seed_id in ["mech_water_heal_seed", "mech_wind_seed", "mech_trial_right_top_random"]:
		var temporary_seed_status := Dictionary(Dictionary(mechanism_status.get("by_id", {})).get(temporary_seed_id, {}))
		_expect(String(temporary_seed_status.get("godot_behavior_status", "")) == "excluded_temporary_trial", "Godot excludes temporary seed/trial mechanism %s from mainline parity work" % temporary_seed_id)
	var none_status := Dictionary(Dictionary(mechanism_status.get("by_id", {})).get("none", {}))
	_expect(String(none_status.get("godot_behavior_status", "")) == "covered", "Godot marks the formal empty mechanism as covered")
	_expect(int(Dictionary(mechanism_status.get("godot_behavior", {})).get("excluded_temporary_trial", 0)) == 13, "Godot reports all temporary Day7 seed/trial mechanisms as excluded")
	_expect(int(Dictionary(mechanism_status.get("godot_behavior", {})).get("excluded_non_formal", 0)) == 27, "Godot excludes non-formal Web mechanic-status leftovers from mainline parity work")
	var followup_groups := Dictionary(mechanism_status.get("godot_followup_group", {}))
	_expect(int(followup_groups.get("future_formal_candidate", 0)) == 27, "Godot classifies all remaining non-formal mechanism leftovers as future formal candidates")
	_expect(int(followup_groups.get("temporary_or_debug_leftover", 0)) == 13, "Godot classifies temporary seed/trial leftovers separately from future formal candidates")
	var water_slow_status := Dictionary(Dictionary(mechanism_status.get("by_id", {})).get("mech_water_slow", {}))
	_expect(String(water_slow_status.get("godot_followup_group", "")) == "future_formal_candidate", "Godot marks pending formal-style water slow as a future formal candidate")
	var fire_trap_status := Dictionary(Dictionary(mechanism_status.get("by_id", {})).get("mech_fire_trap", {}))
	_expect(String(fire_trap_status.get("godot_followup_group", "")) == "temporary_or_debug_leftover", "Godot keeps temporary fire trap in the debug/temporary bucket")
	_expect(int(Dictionary(mechanism_status.get("godot_behavior", {})).get("pending", 0)) == 0, "Godot has no pending formal or non-formal mechanism rows after pruning leftovers")
	_expect(int(Dictionary(mechanism_status.get("godot_behavior", {})).get("not_covered", 0)) == 0, "Godot mechanism status has no unclassified not-covered implemented rows")
	_expect(state.skill_label("summonFromCell") == "格位召唤", "formal summonFromCell skill exposes a Chinese label")
	_expect(state.skill_description("summonFromCell").contains("召唤行动"), "formal summonFromCell skill exposes a Chinese description")
	_expect(not Dictionary(initial["data_counts"]).has("day7_trial_units"), "Godot snapshot no longer exposes Day7 trial unit data")
	_expect(not Dictionary(initial["data_counts"]).has("trial_actions"), "Godot snapshot no longer exposes trial action data")
	_expect(not Dictionary(initial["data_counts"]).has("trial_victory_rules"), "Godot snapshot no longer exposes trial victory rule data")
	_expect(not initial.has("day7Trial"), "Godot snapshot no longer exposes temporary Day7 trial state")
	_expect(int(Dictionary(initial["data_counts"]).get("events", 0)) == 16, "Godot exports only formal event rows and excludes temporary construction filler events")
	_expect(_economy_event(state, "evt_mix_17").is_empty(), "Godot excludes temporary construction filler event evt_mix_17")
	_expect(not _economy_events_contain_text(state, "临时构筑补强"), "Godot exported economy events do not expose temporary construction filler text")
	var first_wave := {}
	var battle_content := Dictionary(state.game_data.get("battle", {}))
	var wave_rows := Array(battle_content.get("waves", []))
	if wave_rows.is_empty() and not Dictionary(battle_content.get("wave", {})).is_empty():
		wave_rows = [Dictionary(battle_content.get("wave", {}))]
	for wave_value in wave_rows:
		var candidate := Dictionary(wave_value)
		if not Array(candidate.get("enemies", [])).is_empty():
			first_wave = candidate
			break
	var first_wave_enemies := Array(first_wave.get("enemies", []))
	if first_wave_enemies.is_empty():
		first_wave_enemies = Array(battle_content.get("enemies", []))
	_expect(first_wave_enemies.size() >= 1, "normal battle wave exports enemies from the monster template table")
	if first_wave_enemies.size() >= 1:
		_expect(String(Dictionary(first_wave_enemies[0]).get("name", "")) != "", "normal battle wave keeps a named first monster template")
	if first_wave_enemies.size() >= 2:
		_expect(String(Dictionary(first_wave_enemies[1]).get("name", "")) != "", "normal battle wave keeps a named second monster template")
		_expect(String(Dictionary(first_wave_enemies[0]).get("id", "")) != String(Dictionary(first_wave_enemies[1]).get("id", "")), "normal battle wave keeps distinct monster identities")
	_expect(_wave_enemy_player_action_field_count(initial) == 0, "normal battle waves do not inherit player pet action fields from temporary clone data")
	_expect(String(Dictionary(initial["build_core"]).get("summary_text", "")) != "", "initial snapshot exposes construction summary")
	_expect(initial["route_options"].size() == 3, "first route schedule exposes three non-battle node choices")
	var initial_run_plan := Dictionary(initial.get("run_plan", {}))
	var initial_run_plan_entries := Array(initial_run_plan.get("entries", []))
	var initial_run_plan_hash := String(initial.get("run_plan_hash", ""))
	_expect(String(initial_run_plan.get("version", "")) == "ysbzs_run_plan_v1", "initial snapshot exposes a full seeded route run_plan")
	_expect(initial_run_plan_entries.size() == int(initial["data_counts"]["route_schedule"]), "run_plan precomputes every formal route schedule entry at run start")
	_expect(initial_run_plan_hash != "", "initial snapshot exposes run_plan_hash")
	if not initial_run_plan_entries.is_empty():
		var first_run_plan_entry := Dictionary(initial_run_plan_entries[0])
		_expect(_option_ids(Array(first_run_plan_entry.get("options", []))) == _option_ids(initial["route_options"]), "visible first route options come from the precomputed run_plan")
	_expect(_action_count(initial, "PICK_NODE") == 3, "initial snapshot exposes three normal route pick actions")
	_expect(_action_count(initial, "RUN_ROUTE_FIXED_BATTLE") == 0, "initial snapshot does not expose battle before the fixed battle schedule step")
	_expect(_first_route_option_by_kind(initial["route_options"], "battle").is_empty(), "first route schedule does not inject a battle option")
	_expect(_has_action(initial, "ENTER_SHOP"), "initial snapshot exposes manual shop action")
	_expect(not _has_action(initial, "RUN_FULL_DAY"), "initial player actions no longer expose full-day automation")
	_expect(not _has_action(initial, "RUN_FULL_RUN"), "initial player actions no longer expose full-run automation")
	var stale_start_state := _new_legacy_state()
	_expect(stale_start_state.roster.size() > 0, "start battle regression fixture has an initial roster pet")
	var stale_start_first_pet := Dictionary(stale_start_state.roster[0])
	var stale_start_first_id := String(stale_start_first_pet.get("id", stale_start_first_pet.get("pet_id", "")))
	for index in range(stale_start_state.roster.size()):
		var stale_pet: Dictionary = Dictionary(stale_start_state.roster[index]).duplicate(true)
		stale_pet["active"] = false
		stale_pet["slot"] = 0
		stale_pet["hp"] = 0
		stale_start_state.roster[index] = stale_pet
	_expect(stale_start_state.dispatch({"type": "START_BATTLE"}), "start battle repairs stale inactive initial roster")
	var stale_start_deployed := stale_start_state.unit_by_id(stale_start_first_id)
	_expect(not stale_start_deployed.is_empty(), "start battle deploys the initial roster pet even when active flags are stale")
	_expect(int(stale_start_deployed.get("hp", 0)) > 0, "start battle deploys the repaired roster pet alive")
	_expect(_alive_player_count(stale_start_state.snapshot()["units"]) >= 1, "start battle has at least one living player pet from repaired roster")
	_expect(Array(initial.get("nextActions", [])).size() == Array(initial.get("next_actions", [])).size(), "snapshot keeps Web-style nextActions alias")
	var adapter_state := _new_legacy_state()
	var adapter_initial := adapter_state.snapshot()
	var rejected_response: Dictionary = adapter_state.run_command({
		"type": "START_BATTLE",
		"baseStateVersion": int(adapter_initial.get("stateVersion", 0)) - 1,
		"commandId": "smoke_adapter_stale"
	})
	_expect(not bool(rejected_response.get("ok", true)), "stale adapter response exposes ok=false")
	_expect(not bool(rejected_response.get("accepted", true)), "stale adapter response exposes accepted=false")
	_expect(String(Dictionary(rejected_response.get("error", {})).get("code", "")) == "STATE_VERSION_MISMATCH", "stale adapter response exposes browser-style error code")
	_expect(Dictionary(rejected_response.get("viewModel", {})).has("gold"), "stale adapter response still returns viewModel")
	_expect(int(adapter_state.snapshot().get("stateVersion", -1)) == int(adapter_initial.get("stateVersion", -1)), "stale adapter response does not advance stateVersion")
	var start_response: Dictionary = adapter_state.run_command({
		"type": "START_BATTLE",
		"baseStateVersion": int(adapter_state.snapshot().get("stateVersion", 0)),
		"commandId": "smoke_adapter_start"
	})
	_expect(bool(start_response.get("ok", false)), "accepted adapter response exposes ok=true")
	_expect(bool(start_response.get("accepted", false)), "accepted adapter response exposes accepted=true")
	_expect(String(start_response.get("command", "")) == "START_BATTLE", "accepted adapter response exposes normalized command")
	_expect(String(Dictionary(start_response.get("commandEnvelope", {})).get("type", "")) == "START_BATTLE", "accepted adapter response exposes commandEnvelope.type")
	_expect(int(start_response.get("stateVersion", -1)) == int(adapter_state.snapshot().get("stateVersion", -2)), "accepted adapter response stateVersion matches snapshot")
	_expect(String(start_response.get("stateHash", "")) == String(adapter_state.snapshot().get("stateHash", "")), "accepted adapter response stateHash matches snapshot")
	var adapter_view_model := Dictionary(start_response.get("viewModel", {}))
	var adapter_snapshot := adapter_state.snapshot()
	_expect(int(adapter_view_model.get("gold", -1)) == int(adapter_snapshot.get("coins", -2)), "adapter viewModel maps Godot coins to Web gold")
	_expect(int(adapter_view_model.get("round", -1)) == int(adapter_snapshot.get("battle_round", -2)), "adapter viewModel maps Godot battle_round to Web round")
	_expect(String(adapter_view_model.get("period", "")) == String(adapter_snapshot.get("battle_period", "")), "adapter viewModel maps Godot battle_period to Web period")
	var adapter_board_cells := Array(Dictionary(adapter_view_model.get("board", {})).get("cells", []))
	_expect(adapter_board_cells.size() == 64, "adapter viewModel exposes board cells")
	if not adapter_board_cells.is_empty():
		var first_adapter_cell := Dictionary(adapter_board_cells[0])
		_expect(first_adapter_cell.has("r"), "adapter board cell exposes Web r alias")
		_expect(first_adapter_cell.has("c"), "adapter board cell exposes Web c alias")
		_expect(first_adapter_cell.has("key"), "adapter board cell exposes Web key")
		_expect(first_adapter_cell.has("unitId"), "adapter board cell exposes Web unitId alias")
		_expect(first_adapter_cell.has("unitSide"), "adapter board cell exposes Web unitSide alias")
	var adapter_units := Array(adapter_snapshot.get("units", []))
	var adapter_player_id := ""
	for adapter_unit in adapter_units:
		var unit := Dictionary(adapter_unit)
		if String(unit.get("side", "")) == "player":
			adapter_player_id = String(unit.get("id", ""))
			break
	_expect(adapter_player_id != "", "adapter fixture has a player unit after START_BATTLE")
	var before_select_version := int(adapter_state.snapshot().get("stateVersion", -1))
	var select_response: Dictionary = adapter_state.run_command({
		"type": "SELECT_UNIT",
		"unitId": adapter_player_id,
		"commandId": "smoke_adapter_select"
	})
	_expect(bool(select_response.get("ok", false)), "view-state adapter response exposes ok=true")
	_expect(bool(select_response.get("accepted", false)), "view-state adapter response exposes accepted=true")
	_expect(not bool(select_response.get("ephemeral", false)), "selection is an authoritative multiplayer-visible command")
	_expect(int(select_response.get("stateVersion", -1)) == before_select_version + 1, "selection advances the authoritative stateVersion")
	_expect(String(Dictionary(Dictionary(select_response.get("viewModel", {})).get("selected", {})).get("unitId", "")) == adapter_player_id, "view-state adapter response maps selected.unitId")
	var before_replay_version := int(adapter_state.snapshot().get("stateVersion", -1))
	var replay_response: Dictionary = adapter_state.run_command({"type": "EXPORT_REPLAY", "commandId": "smoke_adapter_replay"})
	_expect(bool(replay_response.get("ok", false)), "read-only replay adapter response exposes ok=true")
	_expect(bool(replay_response.get("accepted", false)), "read-only replay adapter response exposes accepted=true")
	_expect(bool(replay_response.get("readOnly", false)), "read-only replay adapter response is marked readOnly")
	_expect(int(replay_response.get("stateVersion", -1)) == before_replay_version, "read-only replay adapter response does not advance stateVersion")
	_expect(String(Dictionary(replay_response.get("result", {})).get("schema", "")) == "ysbzs.replay", "read-only replay adapter response puts replay document in result")
	var save_doc := adapter_state.save_document()
	var save_state := Dictionary(save_doc.get("state", {}))
	_expect(int(save_state.get("gold", -1)) == int(save_state.get("coins", -2)), "save payload exposes Web gold alias beside Godot coins")
	_expect(int(save_state.get("round", -1)) == int(save_state.get("battle_round", -2)), "save payload exposes Web round alias beside Godot battle_round")
	_expect(String(save_state.get("period", "")) == String(save_state.get("battle_period", "")), "save payload exposes Web period alias beside Godot battle_period")
	var same_seed_state := _new_legacy_state()
	_expect(_option_ids(initial["route_options"]) == _option_ids(same_seed_state.snapshot()["route_options"]), "same seed produces stable first route options")
	_expect(String(same_seed_state.snapshot().get("run_plan_hash", "")) == initial_run_plan_hash, "same seed produces the same full run_plan hash")
	var alternate_seed_state := _new_legacy_state()
	alternate_seed_state.set_run_seed("ysbzs-smoke-alt")
	_expect(_option_ids(initial["route_options"]) != _option_ids(alternate_seed_state.snapshot()["route_options"]), "different seed can change first route option order")
	_expect(String(alternate_seed_state.snapshot().get("run_plan_hash", "")) != initial_run_plan_hash, "different seed can change the full run_plan hash")
	_expect(_has_option(initial["route_options"], "node_reward_pet"), "first route options include CSV reward node")
	_expect(_has_option(initial["route_options"], "node_shop_basic"), "first route options include CSV shop node")
	var route_alias_state := _new_legacy_state()
	var route_alias_version_before := int(route_alias_state.snapshot().get("stateVersion", -1))
	var route_alias_log_before := Array(route_alias_state.snapshot().get("command_log", [])).size()
	_expect(route_alias_state.dispatch({"type": "generateNodeOptions"}), "Godot normalizes browser generateNodeOptions alias")
	_expect(route_alias_state.dispatch({"type": "generateBattleOptions"}), "Godot normalizes browser generateBattleOptions alias")
	_expect(route_alias_state.dispatch({"type": "rewardOptions", "poolId": "reward_pT1", "count": 3}), "Godot normalizes browser rewardOptions alias")
	_expect(int(route_alias_state.snapshot().get("stateVersion", -1)) == route_alias_version_before, "route/reward option generation aliases do not advance stateVersion")
	_expect(Array(route_alias_state.snapshot().get("command_log", [])).size() == route_alias_log_before, "route/reward option generation aliases stay out of command_log")
	var full_day_alias_response := route_alias_state.run_command({"type": "runFullPlayerDayFlow"})
	_expect(bool(full_day_alias_response.get("accepted", false)), "Godot normalizes browser runFullPlayerDayFlow alias to an accepted command envelope")
	_expect(_command_log_contains_type(Array(route_alias_state.snapshot().get("command_log", [])), "RUN_FULL_DAY"), "runFullPlayerDayFlow alias records canonical RUN_FULL_DAY command identity")
	var reward_alias_state := _new_legacy_state()
	_expect(reward_alias_state.dispatch({"type": "PICK_NODE", "nodeId": "node_reward_pet"}), "reward alias fixture can enter CSV reward node")
	_expect(reward_alias_state.dispatch({"type": "pickReward", "index": 0}), "Godot normalizes browser pickReward alias")
	_expect(reward_alias_state.snapshot()["phase"] == "route", "pickReward alias claims reward and returns to route")
	return {
		"state": state,
		"initial_state_hash": initial_state_hash,
	}
