extends "res://tests/helpers/singleplayer_smoke_suite.gd"


func _run() -> void:
	var trial_state := _new_legacy_state()
	_expect(not trial_state.dispatch({"type": "setupDay7FireTrial"}), "Godot no longer implements temporary Day7 setup alias")
	_expect(not trial_state.dispatch({"type": "runDay7FireTurn1"}), "Godot no longer implements temporary Day7 turn alias")
	_expect(not trial_state.dispatch({"type": "runDay7FireTrialAll"}), "Godot no longer implements temporary Day7 run-all alias")
	var route_state := _new_legacy_state()
	_expect(route_state.dispatch({"type": "PICK_NODE", "nodeId": "node_shop_basic"}), "route smoke can enter first CSV shop")
	var route_shop_seed_audit := Array(route_state.snapshot().get("shop_seed_audit", []))
	_expect(route_shop_seed_audit.size() >= 1, "route shop entry records deterministic shop seed audit")
	var route_shop_seed_entry := Dictionary(route_shop_seed_audit.back())
	_expect(String(route_shop_seed_entry.get("mode", "")) == "route_context", "route shop seed audit records route-context mode")
	_expect(String(route_shop_seed_entry.get("seed_context", "")).begins_with("route:"), "route shop seed audit records route seed context")
	_expect(String(route_shop_seed_entry.get("seed", "")).begins_with("shop:v2:"), "route shop seed audit records the concrete shop RNG seed")
	var route_shop_seed_before_refresh := String(route_shop_seed_entry.get("seed", ""))
	var route_shop_context_roll_before := int(Dictionary(route_state.snapshot().get("rng", {})).get("shop_context_roll_count", -1))
	_expect(_has_action(route_state.snapshot(), "ROLL_SHOP"), "shop snapshot exposes reroll action")
	_expect(_has_action(route_state.snapshot(), "EXIT_SHOP"), "shop snapshot exposes exit action")
	_expect(_action_count(route_state.snapshot(), "BUY_OFFER") >= 1, "shop snapshot exposes buy offer actions")
	var route_freeze_offer_id := _first_buyable_offer_id(route_state)
	_expect(route_freeze_offer_id != "", "shop seed audit fixture has a buyable offer")
	var route_offers_before_freeze := _offer_pet_ids(route_state.snapshot())
	_expect(route_state.dispatch({"type": "FREEZE_OFFER", "offer_id": route_freeze_offer_id}), "shop seed audit can freeze an offer")
	_expect(_offer_pet_ids(route_state.snapshot()) == route_offers_before_freeze, "freezing a shop offer does not reroll deterministic offer order")
	_expect(int(Dictionary(route_state.snapshot().get("rng", {})).get("shop_context_roll_count", -1)) == route_shop_context_roll_before, "freezing a shop offer does not advance route-context shop RNG counter")
	_expect(route_state.dispatch({"type": "ROLL_SHOP", "free": true}), "shop seed audit can refresh route-context shop")
	var route_shop_seed_audit_after_refresh := Array(route_state.snapshot().get("shop_seed_audit", []))
	var route_shop_seed_after_refresh := String(Dictionary(route_shop_seed_audit_after_refresh.back()).get("seed", ""))
	_expect(route_shop_seed_after_refresh != route_shop_seed_before_refresh, "refreshing a route-context shop advances the deterministic shop seed")
	_expect(int(Dictionary(route_state.snapshot().get("rng", {})).get("shop_context_roll_count", -1)) == route_shop_context_roll_before + 1, "refreshing a route-context shop advances the context RNG counter once")
	_expect(route_state.dispatch({"type": "EXIT_SHOP"}), "route smoke can leave first CSV shop")
	_advance_one_route_node_for_smoke(route_state, "route smoke can finish the second ordinary route node")
	var route_battle_option := _first_route_option_by_kind(Array(route_state.snapshot().get("route_options", [])), "battle")
	_expect(not route_battle_option.is_empty(), "route smoke exposes a battle option at the fixed battle schedule step")
	_expect(route_state.dispatch({"type": "RUN_ROUTE_FIXED_BATTLE", "optionId": String(route_battle_option.get("optionId", route_battle_option.get("id", "")))}), "route smoke can enter CSV battle from the fixed battle schedule step")
	_expect(String(route_state.snapshot()["active_encounter"]["encounterId"]) == String(route_battle_option.get("encounterId", "")), "active encounter is stored on fixed battle start")
	var route_gold_before := int(route_state.snapshot()["coins"])
	var route_node_before := int(route_state.snapshot()["node_index"])
	_clear_battle_to_result(route_state)
	_expect(route_state.snapshot()["phase"] == "battle_end", "route battle stops at visible battle result phase")
	_expect(_has_action(route_state.snapshot(), "CONTINUE_AFTER_BATTLE"), "battle result snapshot exposes continue action")
	_expect(bool(route_state.snapshot()["battle_result"]["win"]), "route battle result records win")
	_expect(int(route_state.snapshot()["battle_result"]["gold_from"]) == route_gold_before, "battle result records gold before reward")
	_expect(int(route_state.snapshot()["battle_result"]["gold_to"]) == route_gold_before + int(route_state.snapshot()["battle_result"]["gold"]), "battle result records gold reward")
	_expect(String(route_state.snapshot()["battle_result"]["base_reward_pool_id"]) == "reward_fast_clear", "fast clear records browser-style base reward pool")
	_expect(_has_post_battle_event(route_state.snapshot()["battle_result"], "evt_battle_bonus"), "fast clear records post-battle event from CSV")
	_expect(bool(route_state.snapshot()["battle_result"]["reward_eligible"]), "winning route battle is reward eligible")
	_expect(String(route_state.snapshot()["battle_result"]["reward_pool_id"]) == "reward_pT1", "empty fast-clear pool falls back to available early reward pool")
	_expect(bool(route_state.snapshot()["battle_result"].get("reward_fallback", false)), "empty fast-clear pool records reward fallback")
	var route_reward_fallback_audit := Array(route_state.snapshot().get("reward_fallback_audit", []))
	_expect(route_reward_fallback_audit.size() >= 1, "reward fallback is recorded in state-level audit log")
	var route_reward_fallback_entry := Dictionary(route_reward_fallback_audit.back())
	_expect(String(route_reward_fallback_entry.get("requested_pool_id", "")) == "reward_fast_clear", "reward fallback audit records requested empty pool")
	_expect(String(route_reward_fallback_entry.get("resolved_pool_id", "")) == "reward_pT1", "reward fallback audit records resolved available pool")
	_expect(String(route_reward_fallback_entry.get("reason", "")) == "requested_pool_empty", "reward fallback audit records explicit reason")
	_expect(route_state.dispatch({"type": "CONTINUE_AFTER_BATTLE"}), "can continue from battle result through public command")
	_expect(route_state.snapshot()["phase"] == "reward", "continuing battle result opens route battle reward claim")
	_expect(route_state.snapshot()["reward_options"].size() == 3, "route battle reward creates three claim options")
	_expect(int(route_state.snapshot()["node_index"]) > route_node_before, "continuing battle result advances route schedule")
	_expect(route_state.dispatch({"type": "PICK_REWARD", "index": 0}), "can claim route battle reward through public command")
	_expect(route_state.snapshot()["phase"] == "route", "claiming route battle reward returns to route")
	var next_day_state := _new_legacy_state()
	_expect(not next_day_state.dispatch({"type": "START_NEXT_DAY"}), "cannot enter next day before current route is complete")
	_drive_current_day_to_end(next_day_state)
	_expect(next_day_state.snapshot()["phase"] == "day_end", "completed day route stops at visible day-end phase")
	_expect(int(next_day_state.snapshot()["day"]) == 1, "day-end phase keeps current day before explicit next-day action")
	_expect(_has_action(next_day_state.snapshot(), "START_NEXT_DAY"), "day-end snapshot exposes public next-day action")
	_expect(int(_first_action(next_day_state.snapshot(), "START_NEXT_DAY").get("defaultPayload", {}).get("day", 0)) == 2, "next-day action carries target day payload")
	_expect(next_day_state.dispatch({"type": "START_NEXT_DAY", "day": 2}), "can enter next day through public next-day command")
	_expect(next_day_state.snapshot()["phase"] == "route", "next-day command returns to route phase")
	_expect(int(next_day_state.snapshot()["day"]) == 2, "next-day command advances to requested day")
	_expect(int(next_day_state.snapshot()["node_index"]) == 1, "next-day command resets route step")
	_expect(Array(next_day_state.snapshot()["route_options"]).size() == 3, "next day exposes route choices")
	var full_day_state := _new_legacy_state()
	_expect(full_day_state.dispatch({"type": "RUN_FULL_DAY"}), "can run current day through public full-day command")
	var full_day_phase := String(full_day_state.snapshot().get("phase", ""))
	_expect(["day_end", "game_over"].has(full_day_phase), "full-day command stops at a visible terminal boundary")
	_expect(int(full_day_state.snapshot()["day"]) == 1, "full-day command keeps current day until explicit next-day action")
	if full_day_phase == "day_end":
		_expect(_has_action(full_day_state.snapshot(), "START_NEXT_DAY"), "day-end full-day result exposes next-day action")
	else:
		_expect(_has_action(full_day_state.snapshot(), "NEW_RUN"), "game-over full-day result exposes new-run action")
	var full_run_state := _new_legacy_state()
	var full_run_ok := full_run_state.dispatch({"type": "RUN_FULL_RUN"})
	if not full_run_ok:
		var full_run_logs := Array(full_run_state.snapshot().get("log_lines", []))
		print("FULL_RUN_DIAGNOSTIC %s" % JSON.stringify({
			"phase": full_run_state.snapshot().get("phase", ""),
			"day": full_run_state.snapshot().get("day", 0),
			"result": full_run_state.last_command_result,
			"logs": full_run_logs.slice(maxi(0, full_run_logs.size() - 12)),
		}))
	_expect(full_run_ok, "can run the whole route through public full-run command")
	_expect(["day_end", "game_over"].has(String(full_run_state.snapshot().get("phase", ""))), "full-run command stops at a visible terminal boundary")
	_expect(int(full_run_state.snapshot().get("day", 1)) > 1 or String(full_run_state.snapshot().get("phase", "")) == "game_over", "full-run command advances beyond the first day or reaches game over")
	var fail_state := _new_legacy_state()
	_expect(fail_state.dispatch({"type": "START_BATTLE"}), "failure fixture can start battle")
	fail_state.hero_hp = 0
	var fail_gold_before := int(fail_state.snapshot()["coins"])
	fail_state._check_battle_end()
	var fail_result := Dictionary(fail_state.snapshot()["battle_result"])
	var fail_audit := Dictionary(fail_result.get("failure_audit", {}))
	_expect(fail_state.snapshot()["phase"] == "battle_end", "player hero death stops at visible battle result phase")
	_expect(not bool(fail_result["win"]), "player hero death records loss")
	_expect(String(fail_audit.get("reason", "")) == "player_hero_dead", "player hero death records the two-player battle failure reason")
	_expect(int(fail_audit.get("hero_hp_from", -1)) == 0 and int(fail_audit.get("hero_hp_to", -1)) == 0, "player hero death audit preserves the authoritative zero HP")
	_expect(bool(fail_audit.get("reward_eligible", true)) == false, "player hero death audit records reward ineligibility")
	_expect(int(fail_result.get("gold", 0)) == 1, "player hero death grants consolation gold")
	_expect(int(fail_result.get("gold_to", 0)) == fail_gold_before + 1, "player hero death updates gold total with consolation reward")
	_expect(int(fail_state.snapshot()["coins"]) == fail_gold_before + 1, "player hero death snapshot stores consolation gold")
	_expect(_has_post_battle_event(fail_result, "evt_battle_fail"), "player hero death records failure post-battle event from CSV")
	_expect(int(fail_result["hero_hp_penalty"]) == 0, "player hero death does not apply a second post-battle HP penalty")
	_expect(int(fail_state.snapshot()["hero_hp"]) == 0, "player hero remains at zero HP")
	_expect(fail_state.dispatch({"type": "CONTINUE_AFTER_BATTLE"}), "can continue after player hero death result")
	_expect(fail_state.snapshot()["phase"] == "game_over", "player hero death enters game over after continue")
	var max_round_state := _new_legacy_state()
	_expect(max_round_state.dispatch({"type": "START_BATTLE"}), "max-round failure fixture can start battle")
	max_round_state.battle_round = StateScript.MAX_BATTLE_ROUNDS
	max_round_state.hero_hp = 10
	max_round_state.enemy_hero_hp = 20
	for unit in max_round_state.units:
		unit["atk"] = 0
		unit["attack"] = 0
	var max_round_hp_before := int(max_round_state.snapshot()["hero_hp"])
	var max_round_gold_before := int(max_round_state.snapshot()["coins"])
	var max_round_castle_before := int(max_round_state.snapshot().get("castleLine", 0))
	var max_round_economy_before := float(max_round_state.snapshot().get("economyMultiplier", 0.0))
	_expect(max_round_state.dispatch({"type": "END_PLAYER_TURN"}), "max-round failure resolves through public end-turn command")
	var max_round_snapshot := max_round_state.snapshot()
	var max_round_result := Dictionary(max_round_snapshot["battle_result"])
	var max_round_audit := Dictionary(max_round_result.get("failure_audit", {}))
	_expect(max_round_snapshot["phase"] == "battle_end", "max-round failure stops at visible battle result phase")
	_expect(not bool(max_round_result.get("win", true)), "max-round result records loss")
	_expect(String(max_round_result.get("reason", "")) == "hero_hp_lower", "round-12 result records lower hero HP reason")
	_expect(String(max_round_audit.get("reason", "")) == "hero_hp_lower", "round-12 failure audit records reason")
	_expect(int(max_round_audit.get("castle_line_from", -1)) == max_round_castle_before, "max-round failure audit records castle line before")
	_expect(int(max_round_audit.get("castle_line_to", -1)) == max_round_castle_before, "round-12 HP comparison does not change castle line")
	_expect(is_equal_approx(float(max_round_audit.get("economy_multiplier_to", 0.0)), max_round_economy_before), "round-12 HP comparison does not decay economy")
	_expect(int(max_round_result.get("gold", 0)) == 1, "max-round failure grants browser-style consolation gold")
	_expect(int(max_round_result.get("gold_to", 0)) == max_round_gold_before + 1, "max-round failure updates gold total with consolation reward")
	_expect(int(max_round_snapshot["coins"]) == max_round_gold_before + 1, "max-round snapshot stores consolation gold")
	_expect(int(max_round_result.get("hero_hp_penalty", -1)) == 0, "max-round failure does not apply party-wipe hero HP penalty")
	_expect(int(max_round_snapshot["hero_hp"]) == max_round_hp_before, "max-round failure keeps hero HP unchanged")
	_expect(int(max_round_snapshot.get("castleLine", 0)) == max_round_castle_before, "round-12 HP comparison keeps castleLine")
	_expect(is_equal_approx(float(max_round_snapshot.get("economyMultiplier", 0.0)), max_round_economy_before), "round-12 HP comparison keeps economyMultiplier")
	_expect(_has_post_battle_event(max_round_result, "evt_battle_fail"), "max-round failure records failure post-battle event from CSV")
	var max_round_event := _post_battle_event(max_round_result, "evt_battle_fail")
	_expect(int(max_round_event.get("castleLineFrom", -1)) == max_round_castle_before, "max-round failure post-battle event records castleLineFrom")
	_expect(int(max_round_event.get("castleLineTo", -1)) == max_round_castle_before, "round-12 failure post-battle event records unchanged castleLineTo")
	_expect(is_equal_approx(float(max_round_event.get("economyMultiplierFrom", 0.0)), max_round_economy_before), "max-round failure post-battle event records economyMultiplierFrom")
	_expect(is_equal_approx(float(max_round_event.get("economyMultiplierTo", 0.0)), max_round_economy_before), "round-12 failure post-battle event records unchanged economyMultiplierTo")
	var reduce_reward_state := _new_legacy_state()
	_expect(reduce_reward_state.dispatch({"type": "START_BATTLE"}), "mech_reduce_reward_if_alive fixture can start battle")
	var reduce_reward_enemy_id := _place_first_enemy(reduce_reward_state, 7, 7, 30)
	var reduce_reward_enemy := reduce_reward_state.unit_by_id(reduce_reward_enemy_id)
	reduce_reward_enemy["mechanics"] = ["mech_reduce_reward_if_alive"]
	reduce_reward_enemy["atk"] = 0
	reduce_reward_state.battle_round = StateScript.MAX_BATTLE_ROUNDS
	reduce_reward_state.hero_hp = 10
	reduce_reward_state.enemy_hero_hp = 20
	var reduce_reward_gold_before := int(reduce_reward_state.snapshot()["coins"])
	_expect(reduce_reward_state.dispatch({"type": "END_PLAYER_TURN"}), "mech_reduce_reward_if_alive resolves through public max-round battle-end flow")
	var reduce_reward_result := Dictionary(reduce_reward_state.snapshot()["battle_result"])
	_expect(int(reduce_reward_result.get("gold", -1)) == 0, "mech_reduce_reward_if_alive reduces consolation reward when its carrier remains alive")
	_expect(int(reduce_reward_result.get("gold_to", -1)) == reduce_reward_gold_before, "mech_reduce_reward_if_alive keeps post-battle gold unchanged after reducing the only consolation coin")
	_expect(_log_contains(reduce_reward_state.snapshot()["log_lines"], "奖励降低"), "mech_reduce_reward_if_alive reward penalty is visible in battle log")
	_expect(Array(reduce_reward_result.get("battle_end_mechanics", [])).size() > 0, "mech_reduce_reward_if_alive records battle-end mechanic evidence")
	var elite_reward_state := _new_legacy_state()
	elite_reward_state.coins = 20
	_expect(elite_reward_state.dispatch({"type": "START_BATTLE"}), "mech_elite_reward_bonus fixture can start battle")
	for unit in elite_reward_state.units:
		if String(unit.get("side", "")) == StateScript.ENEMY:
			unit["mechanics"] = ["mech_elite_reward_bonus"]
			unit["elite"] = true
			unit["hp"] = 0
			break
	_clear_battle_to_result(elite_reward_state)
	var elite_reward_result := Dictionary(elite_reward_state.snapshot()["battle_result"])
	var elite_extra_rewards := Array(elite_reward_result.get("extra_rewards", []))
	_expect(elite_extra_rewards.size() > 0 and String(Dictionary(elite_extra_rewards[0]).get("reward_id", "")) == "elite_chest", "mech_elite_reward_bonus records elite_chest extra reward on win")
	_expect(_log_contains(elite_reward_state.snapshot()["log_lines"], "击败精英"), "mech_elite_reward_bonus reward is visible in battle log")
	var game_over_state := _new_legacy_state()
	game_over_state.hero_hp = 5
	_expect(game_over_state.dispatch({"type": "START_BATTLE"}), "game over fixture can start battle")
	game_over_state.hero_hp = 0
	game_over_state._check_battle_end()
	_expect(bool(game_over_state.snapshot()["battle_result"]["game_over"]), "zero hero HP marks battle result as game over")
	_expect(game_over_state.dispatch({"type": "CONTINUE_AFTER_BATTLE"}), "can continue terminal battle result")
	_expect(game_over_state.snapshot()["phase"] == "game_over", "terminal battle result enters game over phase")
	_expect(_has_action(game_over_state.snapshot(), "NEW_RUN"), "game-over snapshot exposes new-run action")
	_expect(game_over_state.dispatch({"type": "NEW_RUN"}), "can restart from game over through public command")
	_expect(game_over_state.snapshot()["phase"] == "route", "new-run command returns to route phase")
	_expect(int(game_over_state.snapshot()["day"]) == 1, "new-run command resets to day one")
	_finish("SMOKE_SINGLEPLAYER_ROUTE_ECONOMY_OK")
